// Generated by pnpm gen:db-types — do not edit manually.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      catalog_programme: {
        Row: {
          code: string
          created_at: string
          id: string
          name: string
          semester_count: number | null
        }
        Insert: {
          code: string
          created_at?: string
          id?: string
          name: string
          semester_count?: number | null
        }
        Update: {
          code?: string
          created_at?: string
          id?: string
          name?: string
          semester_count?: number | null
        }
        Relationships: []
      }
      catalog_subject: {
        Row: {
          activities: Json
          catalog_id: string | null
          catalog_programme_id: string
          created_at: string
          id: string
          module_code: string | null
          module_name: string
          semester_number: number
        }
        Insert: {
          activities?: Json
          catalog_id?: string | null
          catalog_programme_id: string
          created_at?: string
          id?: string
          module_code?: string | null
          module_name: string
          semester_number: number
        }
        Update: {
          activities?: Json
          catalog_id?: string | null
          catalog_programme_id?: string
          created_at?: string
          id?: string
          module_code?: string | null
          module_name?: string
          semester_number?: number
        }
        Relationships: [
          {
            foreignKeyName: "catalog_subject_catalog_programme_id_fkey"
            columns: ["catalog_programme_id"]
            isOneToOne: false
            referencedRelation: "catalog_programme"
            referencedColumns: ["id"]
          },
        ]
      }
      lecturer_availability: {
        Row: {
          created_at: string
          name: string
          notes: string
          preferred_days: number[]
          preferred_slots: string[]
          unavailable_dates: string[]
          unavailable_days: number[]
          unavailable_slots: string[]
          updated_at: string
          usos_id: string
        }
        Insert: {
          created_at?: string
          name: string
          notes?: string
          preferred_days?: number[]
          preferred_slots?: string[]
          unavailable_dates?: string[]
          unavailable_days?: number[]
          unavailable_slots?: string[]
          updated_at?: string
          usos_id: string
        }
        Update: {
          created_at?: string
          name?: string
          notes?: string
          preferred_days?: number[]
          preferred_slots?: string[]
          unavailable_dates?: string[]
          unavailable_days?: number[]
          unavailable_slots?: string[]
          updated_at?: string
          usos_id?: string
        }
        Relationships: []
      }
      plan: {
        Row: {
          created_at: string
          id: string
          level: string | null
          name: string | null
          programme_code: string | null
          programme_name: string | null
        }
        Insert: {
          created_at?: string
          id?: string
          level?: string | null
          name?: string | null
          programme_code?: string | null
          programme_name?: string | null
        }
        Update: {
          created_at?: string
          id?: string
          level?: string | null
          name?: string | null
          programme_code?: string | null
          programme_name?: string | null
        }
        Relationships: []
      }
      plan_ownership: {
        Row: {
          created_at: string
          plan_id: string
          role: string
          user_id: string
        }
        Insert: {
          created_at?: string
          plan_id: string
          role?: string
          user_id: string
        }
        Update: {
          created_at?: string
          plan_id?: string
          role?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "plan_ownership_plan_id_fkey"
            columns: ["plan_id"]
            isOneToOne: false
            referencedRelation: "plan"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "plan_ownership_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      plan_schedule_entry: {
        Row: {
          created_at: string
          end_date_time: string
          id: string
          plan_semester_subject_group_id: string
          room_usos_id: string | null
          start_date_time: string
        }
        Insert: {
          created_at?: string
          end_date_time: string
          id?: string
          plan_semester_subject_group_id: string
          room_usos_id?: string | null
          start_date_time: string
        }
        Update: {
          created_at?: string
          end_date_time?: string
          id?: string
          plan_semester_subject_group_id?: string
          room_usos_id?: string | null
          start_date_time?: string
        }
        Relationships: [
          {
            foreignKeyName: "plan_schedule_entry_plan_semester_subject_group_id_fkey"
            columns: ["plan_semester_subject_group_id"]
            isOneToOne: false
            referencedRelation: "plan_semester_subject_group"
            referencedColumns: ["id"]
          },
        ]
      }
      plan_semester: {
        Row: {
          created_at: string
          end_date: string | null
          id: string
          number: number
          plan_id: string
          start_date: string | null
        }
        Insert: {
          created_at?: string
          end_date?: string | null
          id?: string
          number: number
          plan_id: string
          start_date?: string | null
        }
        Update: {
          created_at?: string
          end_date?: string | null
          id?: string
          number?: number
          plan_id?: string
          start_date?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "plan_semester_plan_id_fkey"
            columns: ["plan_id"]
            isOneToOne: false
            referencedRelation: "plan"
            referencedColumns: ["id"]
          },
        ]
      }
      plan_semester_day_layout: {
        Row: {
          date: string
          id: string
          plan_semester_id: string
          slots: Json
        }
        Insert: {
          date: string
          id?: string
          plan_semester_id: string
          slots?: Json
        }
        Update: {
          date?: string
          id?: string
          plan_semester_id?: string
          slots?: Json
        }
        Relationships: [
          {
            foreignKeyName: "plan_semester_day_layout_plan_semester_id_fkey"
            columns: ["plan_semester_id"]
            isOneToOne: false
            referencedRelation: "plan_semester"
            referencedColumns: ["id"]
          },
        ]
      }
      plan_semester_subject: {
        Row: {
          created_at: string
          ects: number | null
          id: string
          module_code: string | null
          module_name: string
          plan_semester_id: string
        }
        Insert: {
          created_at?: string
          ects?: number | null
          id?: string
          module_code?: string | null
          module_name: string
          plan_semester_id: string
        }
        Update: {
          created_at?: string
          ects?: number | null
          id?: string
          module_code?: string | null
          module_name?: string
          plan_semester_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "plan_semester_subject_plan_semester_id_fkey"
            columns: ["plan_semester_id"]
            isOneToOne: false
            referencedRelation: "plan_semester"
            referencedColumns: ["id"]
          },
        ]
      }
      plan_semester_subject_group: {
        Row: {
          activity_kind: string
          created_at: string
          group_index: number
          hours_total: number
          id: string
          label: string | null
          lecturer_usos_id: string | null
          plan_semester_subject_id: string
        }
        Insert: {
          activity_kind: string
          created_at?: string
          group_index: number
          hours_total: number
          id?: string
          label?: string | null
          lecturer_usos_id?: string | null
          plan_semester_subject_id: string
        }
        Update: {
          activity_kind?: string
          created_at?: string
          group_index?: number
          hours_total?: number
          id?: string
          label?: string | null
          lecturer_usos_id?: string | null
          plan_semester_subject_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "plan_semester_subject_group_lecturer_usos_id_fkey"
            columns: ["lecturer_usos_id"]
            isOneToOne: false
            referencedRelation: "lecturer_availability"
            referencedColumns: ["usos_id"]
          },
          {
            foreignKeyName: "plan_semester_subject_group_plan_semester_subject_id_fkey"
            columns: ["plan_semester_subject_id"]
            isOneToOne: false
            referencedRelation: "plan_semester_subject"
            referencedColumns: ["id"]
          },
        ]
      }
      users: {
        Row: {
          created_at: string
          id: string
          updated_at: string
          usos_user_id: string
        }
        Insert: {
          created_at?: string
          id: string
          updated_at?: string
          usos_user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          updated_at?: string
          usos_user_id?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
